#ifndef WAVE_DATA_CONSTANTS_HPP
#define WAVE_DATA_CONSTANTS_HPP

#include "CONSTANTS/TYPE.hpp"

namespace CONSTANTS::WAVES {

using BLOON = CONSTANTS::TYPE::BLOON;

// generated wave data through python
inline const std::array<std::vector<BLOON>, 50> WAVE_DATA = {{
	// Wave 1
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED
	},
	// Wave 2
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED
	},
	// Wave 3
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE
	},
	// Wave 4
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE
	},
	// Wave 5
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE
	},
	// Wave 6
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN
	},
	// Wave 7
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE
	},
	// Wave 8
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE
	},
	// Wave 9
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN
	},
	// Wave 10
	{
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN
	},
	// Wave 11
	{
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW
	},
	// Wave 12
	{BLOON::RAINBOW},
	// Wave 13
	{
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED, BLOON::RED,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN
	},
	// Wave 14
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::RAINBOW
	},
	// Wave 15
	{
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 16
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 17
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 18
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 19
	{
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 20
	{BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD},
	// Wave 21
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 22
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW
	},
	// Wave 23
	{
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 24
	{
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE,
		BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::BLUE, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN,
		BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::GREEN, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW
	},
	// Wave 25
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK
	},
	// Wave 26
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD
	},
	// Wave 27
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK
	},
	// Wave 28
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE
	},
	// Wave 29
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD
	},
	// Wave 30
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK
	},
	// Wave 31
	{BLOON::CERAMIC, BLOON::CERAMIC},
	// Wave 32
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE
	},
	// Wave 33
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 34
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 35
	{
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW
	},
	// Wave 36
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD
	},
	// Wave 37
	{BLOON::MOAB},
	// Wave 38
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 39
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW
	},
	// Wave 40
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 41
	{
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW
	},
	// Wave 42
	{
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW, BLOON::YELLOW,
		BLOON::YELLOW, BLOON::YELLOW, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 43
	{
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 44
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::MOAB
	},
	// Wave 45
	{
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 46
	{
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC
	},
	// Wave 47
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 48
	{
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK,
		BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::BLACK, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE,
		BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::WHITE, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW
	},
	// Wave 49
	{
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC
	},
	// Wave 50
	{
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD, BLOON::LEAD,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW,
		BLOON::RAINBOW, BLOON::RAINBOW, BLOON::RAINBOW, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC, BLOON::CERAMIC,
		BLOON::CERAMIC, BLOON::CERAMIC, BLOON::MOAB, BLOON::MOAB
	}
}};

}

#endif